### ISSUE TITLE
France ban communism through an event and still has the decision (note probably same for Belgium)

### ISSUE THREAD

**Issue by Thinking-waffle** [deliciousmods/1956_beta#111]

**Comment by Greatexperiment** [comment]
This issue has now been partially addressed, but it's up to you if you want to close it.

**Comment by Zurich899** [comment]
I just made a pull request that will stop France from getting the ban communism event if it bans communism through a decision (by adding a minimum 5% communism requirement to the trigger) and it seems to work in testing. I think that this issue can be closed if the pull request is accepted, since the decision and event for France are mutually exclusive, and Belgium's relationship to communism is being handled as part of Waffles' Belgium overhaul.

**Comment by Tyguy9112** [comment]
Reply, if issue reoccurs.
