### ISSUE TITLE
Overreliance of localisation on the /replace folder

### ISSUE THREAD

**Issue by Warlider** [deliciousmods/1956_beta#2822]
Issue has seemingly plagued R56 since before 2021.
https://github.com/deliciousmods/1956_beta/commit/cbf7723425fdfa9b2143cc140acd79be9b989f43

Localisation that does not have to be in the /english/replace folder is in the /replace folder, making it impossible to replace singular strings for submods, creating unnecessary work by poor practices of the parent mod.

For anyone who does not know:
Localisation keys inside /replace will be used to override localisation for vanilla and r56. This makes possible replacing or correcting localisation in vanilla on a per-key basis, instead of overriding entire files. This practice should not be used for new additions, as the game takes every single localisation key inside the /replace folder and assigns to it a higher priority than necessary.

Effect of this practice, is that any new addition of road is localised with a priority that cannot be overriden on a per-key basis for submods, creating unnecessary workload having to keep entire batches of localisation up-to-date.

As an example:
r56e_technology_l_english.yml is full of unnecessary overrides, as it primarily localises new road additions.
future_radar to future_radar_2 is new tech, there is no future_radar in vanilla, so localisation keys for it should be in the /english instead of /english/replace.

If as a submod i wanted to change the text for radar tech, i have to override the entire r56e_technologies yml file, instead of creating any yml file i want and localising in it an override. In effect, what is a single line of text to override becomes a 50kb nightmare of monthly checks to see if anything changed in addition to my overrides.

This also creates unnecessary localisation bloat, as the override to 4 lines is 1.73kb and one is forced to use the entire 50kb file. On its own its not much but it will and does compound.

A rework to remedy this situation WILL be hell, as it will require a review of 2 years of localisation files duped into /english/replace and there will be files that both replace localisation keys AND add localisation for new keys, but i still strongly urge to do this review and cease adding new content to the /replace folder.

**Comment by SpicyAlfredo** [comment]
Hey Warlinder, thanks for the write up. The practice is definitely a black eye on how we handle localization. The mod development team around the time the practice started (which include me) was smaller then it was now, and was no way able to keep up with the maintenance creep for a mod of our size. We took a lot of short cuts that are baring their ugly head ever so often. We didn't have the foresight that sub mods would make the sweeping changes that RP mods do. This is an issue that will definitely will be discussed and will update you on. In the meantime could you tell me what are the most problematic files in the replace folder for RP mods?

**Comment by Warlider** [comment]
Shortcuts are absolutely understandable, basically the reason for this entire writeup is so me and other submods can utilise the shortcuts and i dont really blame anyone in particular for continuing this "Tradition" since 2021, but seeing as there is no real reason to continue this and it creates hassle for "the little guys" i did feel it prudent to bring up and i hope it will be discontinued.

My current object of woes is the r56e_technology file i used as the example as i didnt find the AN/APS-2 4 and 6 name realistically or historically accurate. Because of the before mentioned issue, 6 lines of edited trivia will require 656 lines of trivia be kept up to date with Road.

(AN/APS-2 being the name for the US 1942/43 antenna, which R56 has slapped on 1945 tech.)

Other than that, i didn't edit any localisation so its not yet a massive pain, but i still urge the review be made as god only knows how many people were faced with a similar issue who didn't think to write a proper report on the matter...

Heck ultimately i wouldn't mind doing such a review myself.

**Comment by SpicyAlfredo** [comment]
I appreciate your concern; the lead devs are looking at the practice as we speak. A lead dev has just offered to take a look at the issue since you brought it up. We were not aware of the issues with this practice until now, it wasn't done out of spite to sub-mods or to make anyone's life harder. I understand why you're frustrated. 

 Due to the lack of devs compared to other large overhaul mods codebase maintenance and updates of practices are done on a must-need basis. Is the mod code up to my standards? Not by a country mile, but the senior devs that do month-to-month maintenance and fixing have to pick their battles since dev time is a valuable resource. Not using it as an excuse, just commenting on why some things are “bad” when it comes to the mods code. I just wanted to state that it’s not due to a lack of care, complacency, or being stuck in our ways. We have no problem changing how we do things when it’s justified, which in this case it is. 

Also in the future, I encourage you to spread the word to your team and other RP modders to use Github/Discord to relay issues with the base mod that seriously affect workflow or need fixing/reform. We don’t know about such issues until they are reported since we are tunnel vision with issues affecting the single-player portion of the HOI4 community. 

Thanks again for the write-ups. You’re also always welcome to come abroad to work on the main mod and do codebase reviews even if your focus would only be on one or two things that want to be adjusted just for the sake of your RP work. We always need more help in whatever size it comes in.

**Comment by Warlider** [comment]
I will be honest, i did not expect change. Very happy with the resolution of this, assuming change will actually come, slow or not. Ill close the ticket.

Happy New Year.

**Comment by marijn211** [comment]
Will look into but low prio
