### ISSUE TITLE
Some guy wants a Dora gun (technology)

### ISSUE THREAD

**Issue by Greatexperiment** [deliciousmods/1956_beta#35]
Add tech via decision, link to previous artillery research. Listed as moderate because there's a fair amount involved.

**Comment by Thinking-waffle** [comment]
Alright, you can look for the calibers and such yourself so here is how I imagine it in game:
If possilble: make the decision cost command points.
If possible: restrict its use to a certain level of infrastructure because in order to function it needed a 360° railway circle to be able to adjust its fire.
Cost, very high 4 tungsten and 4 steel (that's just a wild guess). logically only one per batallion. It should include support equipment too because of the engineers needed to build those railways circles in addition to all the artillerymen and other people charged with bringing massive shalls to the gun itself.

Only one for each batallion, bonus to bunker destruction, especially if recon is high enough (don't know if it's possible). Should perform relatively well with the siege artillery order.

**Comment by Greatexperiment** [comment]
I'll look into it after the current patch. It might be a nice template for future "special research actions"

I'm also doing this largely so that I can have a Sarcasm Gun.

**Comment by Thinking-waffle** [comment]
I forgot to mention that it should be vulnerable to tactical bombing (not so much to CAS because it should logically be away from the front)

**Comment by Tyguy9112** [comment]
Reply, if you want reopened
